version: '3.8'
services:
  profile_app:
    image: profile_dev:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://db:27017/profile'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mongo:3.5
    environment:
      - MONGO_URI=profile
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
